// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/audit" | "/llm" | "/login" | "/logs" | "/mcp" | "/skills" | "/sso" | "/tenant" | "/users"
type AppRouteHandlerRoutes = "/api/admin/audit" | "/api/admin/llm/active" | "/api/admin/llm/providers" | "/api/admin/llm/providers/[id]" | "/api/admin/llm/providers/[id]/test" | "/api/admin/logs" | "/api/admin/logs/export" | "/api/admin/mcp/servers" | "/api/admin/mcp/servers/[id]" | "/api/admin/mcp/servers/[id]/enabled" | "/api/admin/organizations" | "/api/admin/organizations/[id]" | "/api/admin/skills" | "/api/admin/skills/[id]" | "/api/admin/skills/[id]/config" | "/api/admin/sso/policy" | "/api/admin/sso/providers" | "/api/admin/sso/providers/[id]" | "/api/client/config/auth" | "/api/client/config/llm" | "/api/client/config/mcp" | "/api/client/config/skills" | "/api/client/logs" | "/api/health" | "/api/v1/admin/llm/providers" | "/api/v1/admin/organizations" | "/api/v1/admin/organizations/[id]/members" | "/api/v1/admin/users" | "/api/v1/admin/users/[id]" | "/api/v1/admin/users/[id]/roles" | "/api/v1/admin/users/invite" | "/api/v1/auth/login" | "/api/v1/auth/logout" | "/api/v1/auth/refresh" | "/api/v1/auth/session" | "/api/v1/client/config/llm" | "/api/v1/client/logs"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/audit": {}
  "/api/admin/llm/active": {}
  "/api/admin/llm/providers": {}
  "/api/admin/llm/providers/[id]": { "id": string; }
  "/api/admin/llm/providers/[id]/test": { "id": string; }
  "/api/admin/logs": {}
  "/api/admin/logs/export": {}
  "/api/admin/mcp/servers": {}
  "/api/admin/mcp/servers/[id]": { "id": string; }
  "/api/admin/mcp/servers/[id]/enabled": { "id": string; }
  "/api/admin/organizations": {}
  "/api/admin/organizations/[id]": { "id": string; }
  "/api/admin/skills": {}
  "/api/admin/skills/[id]": { "id": string; }
  "/api/admin/skills/[id]/config": { "id": string; }
  "/api/admin/sso/policy": {}
  "/api/admin/sso/providers": {}
  "/api/admin/sso/providers/[id]": { "id": string; }
  "/api/client/config/auth": {}
  "/api/client/config/llm": {}
  "/api/client/config/mcp": {}
  "/api/client/config/skills": {}
  "/api/client/logs": {}
  "/api/health": {}
  "/api/v1/admin/llm/providers": {}
  "/api/v1/admin/organizations": {}
  "/api/v1/admin/organizations/[id]/members": { "id": string; }
  "/api/v1/admin/users": {}
  "/api/v1/admin/users/[id]": { "id": string; }
  "/api/v1/admin/users/[id]/roles": { "id": string; }
  "/api/v1/admin/users/invite": {}
  "/api/v1/auth/login": {}
  "/api/v1/auth/logout": {}
  "/api/v1/auth/refresh": {}
  "/api/v1/auth/session": {}
  "/api/v1/client/config/llm": {}
  "/api/v1/client/logs": {}
  "/audit": {}
  "/llm": {}
  "/login": {}
  "/logs": {}
  "/mcp": {}
  "/skills": {}
  "/sso": {}
  "/tenant": {}
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
